mod model; mod math; mod storage; mod prayer;
use model::{AppData,Entry,Page,Sheet};
use wasm_bindgen::JsCast;
use yew::prelude::*;
use web_sys::{HtmlInputElement,HtmlTextAreaElement};

fn today()->String { (chrono::Utc::now()+chrono::Duration::hours(6)).format("%Y-%m-%d").to_string() }
fn value(e:InputEvent)->String{e.target_unchecked_into::<HtmlInputElement>().value()}
fn area(e:InputEvent)->String{e.target_unchecked_into::<HtmlTextAreaElement>().value()}
fn uuid()->String{format!("{}-{}",js_sys::Date::now() as u64,js_sys::Math::random())}
fn input(label:&str, v:&str, on:Callback<InputEvent>, ty:&str)->Html{html!{<label class="field"><span>{label}</span><input type={ty.to_string()} value={v.to_owned()} oninput={on}/></label>}}

#[function_component(App)]
fn app()->Html{
 let data=use_state(storage::load);let route=use_state(||Page::Dashboard);let drawer=use_state(||false);let editing=use_state(||None::<String>);let title=use_state(String::new);let body=use_state(String::new);let mood=use_state(String::new);let tags=use_state(String::new);let place=use_state(String::new);let day=use_state(today);let notice=use_state(String::new);let month=use_state(||today()[..7].to_owned());let calc=use_state(String::new);let online=use_state(String::new);let weight=use_state(String::new);let height=use_state(String::new);let age=use_state(String::new);let sheet=use_state(||vec![String::new();24]);let prayer_location=use_state(||0usize);let karachi=use_state(||true);let hanafi=use_state(||true);
 let navigate={let route=route.clone();let drawer=drawer.clone();let editing=editing.clone();Callback::from(move|p:Page|{route.set(p);drawer.set(false);editing.set(None);if let Some(w)=web_sys::window(){let _=w.history().and_then(|h|h.push_state_with_url(&wasm_bindgen::JsValue::NULL,"",Some(&format!("#{}",p.slug()))));}})};
 {let route=route.clone();use_effect_with((),move |_|{let cb=wasm_bindgen::closure::Closure::<dyn FnMut(_)>::new(move|_:web_sys::Event|{let p=web_sys::window().and_then(|w|w.location().hash().ok()).map(|h|Page::from_slug(h.trim_start_matches('#'))).unwrap_or(Page::Dashboard);route.set(p)});if let Some(w)=web_sys::window(){let _=w.add_event_listener_with_callback("popstate",cb.as_ref().unchecked_ref());}move||{if let Some(w)=web_sys::window(){let _=w.remove_event_listener_with_callback("popstate",cb.as_ref().unchecked_ref());}drop(cb)}});}
 let persist={let data=data.clone();let notice=notice.clone();Callback::from(move|d:AppData|{match storage::save(&d){Ok(())=>{data.set(d);notice.set("Saved on this device".into())},Err(e)=>notice.set(e)}})};
 let current=*route; let navbtn=|p:Page,label:&str|{let nav=navigate.clone();html!{<button class="button subtle" onclick={Callback::from(move |_|nav.emit(p))}>{label}</button>}};
 let counts=|k:&str|data.entries.iter().filter(|e|e.kind==k).count();
 let content=match current {
  Page::Dashboard=>{let cards=[("Journal",counts("Journal"),Page::Journal,"✎"),("Activities",counts("Activities"),Page::Activities,"⚡"),("Thoughts",counts("Thoughts"),Page::Thoughts,"✧"),("Goals",counts("Goals"),Page::Goals,"◎")];html!{<><section class="hero"><span class="eyebrow">{"WELCOME BACK · MR.MUNNA"}</span><h2>{"Your life. Your story."}</h2><p>{"A beautiful place for the moments, ideas, and ambitions that make you you."}</p><div class="hero-actions">{navbtn(Page::Journal,"Write a journal")} {navbtn(Page::Calendar,"Open calendar")}</div></section><div class="stats">{for cards.into_iter().map(|(label,n,p,icon)|{let nav=navigate.clone();html!{<button class="stat" onclick={Callback::from(move |_|nav.emit(p))}><span>{icon}</span><small>{label}</small><strong>{n}</strong></button>}})}</div><div class="section-head"><span class="eyebrow">{"QUICK CAPTURE"}</span><h3>{"Start where you are"}</h3></div><div class="tile-grid">{for [(Page::Journal,"A new journal","Capture a moment","✎"),(Page::Thoughts,"A passing thought","Give it a home","✧"),(Page::Activities,"Log an activity","Keep moving","⚡"),(Page::Prayer,"Prayer time","Pause and reconnect","◴")].into_iter().map(|(p,t,s,i)|{let nav=navigate.clone();html!{<button class="tile" onclick={Callback::from(move |_|nav.emit(p))}><span class="tile-icon">{i}</span><b>{t}</b><small>{s}</small><span class="arrow">{"↗"}</span></button>}})}</div></>}},
  Page::Journal|Page::Activities|Page::Thoughts|Page::Goals|Page::Nutrition=>{
   let kind=current.title().to_owned();let entries:Vec<Entry>=data.entries.iter().filter(|e|e.kind==kind).cloned().collect();let is_editing=(*editing).is_some();
   let start={let editing=editing.clone();let title=title.clone();let body=body.clone();let mood=mood.clone();let tags=tags.clone();let place=place.clone();let day=day.clone();Callback::from(move|e:Option<Entry>|{editing.set(Some(e.as_ref().map(|x|x.id.clone()).unwrap_or_default()));title.set(e.as_ref().map(|x|x.title.clone()).unwrap_or_default());body.set(e.as_ref().map(|x|x.body.clone()).unwrap_or_default());mood.set(e.as_ref().map(|x|x.mood.clone()).unwrap_or_default());tags.set(e.as_ref().map(|x|x.tags.clone()).unwrap_or_default());place.set(e.as_ref().map(|x|x.place.clone()).unwrap_or_default());day.set(e.as_ref().map(|x|x.date.clone()).unwrap_or_else(today));})};
   let save={let data=data.clone();let persist=persist.clone();let editing=editing.clone();let title=title.clone();let body=body.clone();let mood=mood.clone();let tags=tags.clone();let place=place.clone();let day=day.clone();let kind=kind.clone();Callback::from(move|_|{if title.trim().is_empty()&&body.trim().is_empty(){return}let mut d=(*data).clone();let id=editing.as_ref().filter(|x|!x.is_empty()).cloned().unwrap_or_else(uuid);let item=Entry{id:id.clone(),kind:kind.clone(),title:(*title).clone(),body:(*body).clone(),date:(*day).clone(),mood:(*mood).clone(),tags:(*tags).clone(),place:(*place).clone(),done:false};if let Some(old)=d.entries.iter_mut().find(|e|e.id==id){*old=item}else{d.entries.insert(0,item)}persist.emit(d);editing.set(None)})};
   html!{<><div class="page-heading"><div><span class="eyebrow">{"YOUR PRIVATE SPACE"}</span><h2>{kind.clone()}</h2><p>{format!("{} saved · moments worth remembering",entries.len())}</p></div><button class="button primary" onclick={let start=start.clone();Callback::from(move |_|start.emit(None))}>{format!("＋ New {}",kind)}</button></div>{if is_editing {html!{<div class="panel editor"><div class="section-head"><h3>{format!("Write {}",kind)}</h3><button class="icon-btn" onclick={let editing=editing.clone();Callback::from(move |_|editing.set(None))}>{"✕"}</button></div><div class="form-grid">{input("Title",&title,{let title=title.clone();Callback::from(move|e|title.set(value(e)))},"text")}{input("Date",&day,{let day=day.clone();Callback::from(move|e|day.set(value(e)))},"date")}{input("Mood",&mood,{let mood=mood.clone();Callback::from(move|e|mood.set(value(e)))},"text")}{input("Place",&place,{let place=place.clone();Callback::from(move|e|place.set(value(e)))},"text")}</div><label class="field"><span>{"Your thoughts"}</span><textarea rows="8" value={(*body).clone()} oninput={let body=body.clone();Callback::from(move|e|body.set(area(e)))}/></label>{input("Tags (comma separated)",&tags,{let tags=tags.clone();Callback::from(move|e|tags.set(value(e)))},"text")}<button class="button primary" onclick={save}>{"Save entry"}</button></div>}}else{html!{<div class="entry-grid">{if entries.is_empty(){html!{<div class="empty"><span>{"✦"}</span><h3>{"A blank page is a beginning."}</h3><p>{"Add your first entry whenever you feel ready."}</p></div>}}else{html!{for entries.into_iter().map(|e|{let edit=start.clone();let del={let data=data.clone();let persist=persist.clone();let id=e.id.clone();Callback::from(move|_|{let mut d=(*data).clone();d.entries.retain(|x|x.id!=id);persist.emit(d)})};html!{<article class="entry panel"><small>{e.date.clone()} {if !e.mood.is_empty(){format!(" · {}",e.mood)}else{String::new()}}</small><h3>{e.title.clone()}</h3><p>{e.body.clone()}</p><div class="entry-actions"><button onclick={let e=e.clone();Callback::from(move |_|edit.emit(Some(e.clone())))}>{"Edit ↗"}</button><button onclick={del}>{"Delete"}</button></div></article>}})}}}</div>}}</>}}
  },
  Page::Calendar=>{let y:i32=month.get(0..4).and_then(|x|x.parse().ok()).unwrap_or(2026);let m:u32=month.get(5..7).and_then(|x|x.parse().ok()).unwrap_or(1);let first=chrono::NaiveDate::from_ymd_opt(y,m,1).unwrap();let start=chrono::Datelike::weekday(&first).num_days_from_sunday();let days=(1..=31).take_while(|day|chrono::NaiveDate::from_ymd_opt(y,m,*day).is_some()).count();let change=|dir:i32|{let month=month.clone();Callback::from(move|_|{let x=y*12+m as i32-1+dir;month.set(format!("{:04}-{:02}",x.div_euclid(12),x.rem_euclid(12)+1))})};html!{<><div class="page-heading"><div><span class="eyebrow">{"EVERY DAY HAS A STORY"}</span><h2>{"Calendar"}</h2></div><div class="row"><button class="icon-btn" onclick={change(-1)}>{"←"}</button><b>{month.to_string()}</b><button class="icon-btn" onclick={change(1)}>{"→"}</button></div></div><div class="panel calendar"><div class="calendar-grid">{for ["SUN","MON","TUE","WED","THU","FRI","SAT"].into_iter().map(|d|html!{<b class="weekday">{d}</b>})}{for (0..start).map(|_|html!{<span/>})}{for (1..=days).map(|d|{let date=format!("{}-{:02}",*month,d);let n=data.entries.iter().filter(|e|e.date==date).count();html!{<div class={if n>0{"date marked"}else{"date"}}><b>{d}</b>{if n>0{html!{<small>{format!("{} notes",n)}</small>}}else{html!{<small>{" "}</small>}}}</div>}})}</div></div></>}},
  Page::Timeline=>html!{<><div class="page-heading"><div><span class="eyebrow">{"LOOK BACK, MOVE FORWARD"}</span><h2>{"Timeline"}</h2></div></div><div class="timeline">{for data.entries.iter().map(|e|html!{<div class="timeline-item panel"><small>{format!("{} · {}",e.date,e.kind)}</small><h3>{e.title.clone()}</h3><p>{e.body.clone()}</p></div>})}</div></>},
  Page::Gallery=>{let birth=chrono::NaiveDate::parse_from_str(&data.birthdate,"%Y-%m-%d").ok();let now=chrono::Utc::now().date_naive();let lived=birth.map(|b|(now-b).num_days().max(0)/7).unwrap_or(0);let total=90*52;let shown=260;html!{<><div class="page-heading"><div><span class="eyebrow">{"THE BIG PICTURE"}</span><h2>{"Life gallery"}</h2><p>{"Every little square is a week of your story."}</p></div></div><div class="stats three"><div class="stat"><small>{"WEEKS LIVED"}</small><strong>{lived}</strong></div><div class="stat"><small>{"CURRENT WEEK"}</small><strong>{lived+1}</strong></div><div class="stat"><small>{"WEEKS REMAINING · 90 YEARS"}</small><strong>{(total-lived).max(0)}</strong></div></div><div class="panel"><h3>{"Your weeks at a glance"}</h3><div class="week-grid">{for (0..shown).map(|i|html!{<span title={format!("Week {}",i+1)} class={if i as i64<lived{"week lived"}else if i as i64==lived{"week current"}else{"week"}}/>})}</div><p class="muted">{"Showing the first five years of the grid; set your birthday in Profile to personalize the colors."}</p></div></>}},
  Page::Body=>{let result=match(weight.parse::<f64>(),height.parse::<f64>(),age.parse::<f64>()){(Ok(w),Ok(h),Ok(a))=>match(math::bmi(w,h),math::bmr(w,h,a,true)){(Some(b),Some(c))=>format!("BMI {:.1} · Estimated resting energy {:.0} kcal/day",b,c),_=>"Enter valid adult measurements".into()},_=>"Enter your measurements to see an estimate".into()};html!{<div class="panel"><span class="eyebrow">{"KNOW YOUR NUMBERS"}</span><h2>{"BMI & BMR"}</h2><p>{"A helpful estimate, not a medical diagnosis."}</p><div class="form-grid">{input("Weight · kg",&weight,{let s=weight.clone();Callback::from(move|e|s.set(value(e)))},"number")}{input("Height · cm",&height,{let s=height.clone();Callback::from(move|e|s.set(value(e)))},"number")}{input("Age · years",&age,{let s=age.clone();Callback::from(move|e|s.set(value(e)))},"number")}</div><div class="result">{result}</div></div>}},
  Page::Calculas=>{let computed=math::calculate(&calc).map(|x|format!("= {}",x)).unwrap_or_default();let save={let data=data.clone();let persist=persist.clone();let sheet=sheet.clone();Callback::from(move|_|{let mut d=(*data).clone();d.sheets.push(Sheet{id:uuid(),title:format!("Sheet {}",d.sheets.len()+1),cells:(*sheet).clone()});persist.emit(d)})};html!{<><div class="page-heading"><div><span class="eyebrow">{"IDEAS INTO NUMBERS"}</span><h2>{"Calculas"}</h2><p>{"A compact worksheet and calculator."}</p></div></div><div class="panel"><h3>{"Quick calculation"}</h3>{input("Expression, e.g. (12+8)*2",&calc,{let calc=calc.clone();Callback::from(move|e|calc.set(value(e)))},"text")}<div class="result">{computed}</div></div><div class="panel"><div class="section-head"><h3>{"Your worksheet"}</h3><button class="button primary" onclick={save}>{"Save sheet"}</button></div><div class="sheet-grid">{for (0..6).flat_map(|row|(0..4).map(move|col|row*4+col)).map(|i|{let sheet=sheet.clone();html!{<label><small>{format!("{}{}",(b'A'+(i%4)as u8)as char,i/4+1)}</small><input value={sheet[i].clone()} oninput={Callback::from(move|e|{let mut v=(*sheet).clone();v[i]=value(e);sheet.set(v)})}/></label>}})}</div><div class="saved-sheets">{for data.sheets.iter().map(|s|{let sh=sheet.clone();let cells=s.cells.clone();html!{<button class="chip" onclick={Callback::from(move |_|sh.set(cells.clone()))}>{s.title.clone()}</button>}})}</div></div></>}},
  Page::Prayer=>{let (city,lat,lon)=prayer::LOCATIONS[*prayer_location];let date=chrono::NaiveDate::parse_from_str(&today(),"%Y-%m-%d").unwrap();let times=prayer::times(date,lat,lon,*karachi,*hanafi);
   let fetch={let online=online.clone();let method=if *karachi{1}else{3};let school=if *hanafi{1}else{0};Callback::from(move|_|{online.set("Checking online prayer times…".into());let online=online.clone();let url=format!("https://api.aladhan.com/v1/timings/{}?latitude={lat}&longitude={lon}&method={method}&school={school}",date.format("%d-%m-%Y"));wasm_bindgen_futures::spawn_local(async move{let result=async{let resp=gloo_net::http::Request::get(&url).send().await.map_err(|e|e.to_string())?;let json:serde_json::Value=resp.json().await.map_err(|e|e.to_string())?;if json["code"].as_i64()!=Some(200){return Err("Prayer service returned an error".into())}let t=&json["data"]["timings"];Ok::<_,String>(format!("AlAdhan · {} · Fajr {} · Dhuhr {} · Asr {} · Maghrib {} · Isha {}",json["data"]["date"]["readable"].as_str().unwrap_or("today"),t["Fajr"].as_str().unwrap_or("—"),t["Dhuhr"].as_str().unwrap_or("—"),t["Asr"].as_str().unwrap_or("—"),t["Maghrib"].as_str().unwrap_or("—"),t["Isha"].as_str().unwrap_or("—")))}.await;online.set(result.unwrap_or_else(|e|format!("Online check unavailable: {e}")))})})};
   html!{<><div class="page-heading"><div><span class="eyebrow">{"A MOMENT TO PAUSE"}</span><h2>{"Clock & prayer"}</h2><p>{"Offline estimates for your location, with a separate manual internet check."}</p></div></div><div class="panel prayer-hero"><span class="eyebrow">{format!("{} · BANGLADESH · UTC+6",city)}</span><h3>{date.format("%A, %d %B %Y").to_string()}</h3><div class="form-grid"><label class="field"><span>{"Location"}</span><select onchange={let location=prayer_location.clone();Callback::from(move|e:Event|{let select:web_sys::HtmlSelectElement=e.target_unchecked_into();location.set(select.value().parse().unwrap_or(0))})}>{for prayer::LOCATIONS.iter().enumerate().map(|(i,(n,_,_))|html!{<option value={i.to_string()} selected={i==*prayer_location}>{*n}</option>})}</select></label><label class="field"><span>{"Method"}</span><select onchange={let state=karachi.clone();Callback::from(move|e:Event|{let select:web_sys::HtmlSelectElement=e.target_unchecked_into();state.set(select.value()=="karachi")})}><option value="karachi" selected={*karachi}>{"Karachi"}</option><option value="mwl" selected={!*karachi}>{"Muslim World League"}</option></select></label></div><label class="check"><input type="checkbox" checked={*hanafi} onchange={let state=hanafi.clone();Callback::from(move|e:Event|{let input:web_sys::HtmlInputElement=e.target_unchecked_into();state.set(input.checked())})}/>{"Hanafi Asr"}</label><h3>{"Offline calculation"}</h3><div class="prayer-grid">{for times.into_iter().map(|(n,t)|html!{<div class="prayer-time"><small>{n}</small><b>{t}</b></div>})}</div><p class="muted">{"Solar calculation is an estimate. Follow your local mosque for authoritative times."}</p><button class="button primary" onclick={fetch}>{"Check prayer times online ↗"}</button><p class="result">{(*online).clone()}</p></div></>}},
  Page::Bangladesh=>html!{<><div class="page-heading"><div><span class="eyebrow">{"HOME & HERITAGE"}</span><h2>{"Bangladesh"}</h2></div></div><div class="tile-grid">{for [("Dhaka","Capital & culture"),("Chattogram","Port city"),("Sylhet","Tea country"),("Rajshahi","Silk city"),("Khulna","Gateway to the Sundarbans"),("Rangpur","Northern heritage"),("Barishal","City of rivers"),("Mymensingh","Art and history")].map(|(a,b)|html!{<div class="tile"><span class="tile-icon">{"◇"}</span><b>{a}</b><small>{b}</small></div>})}</div></>},
  Page::Profile=>{let save={let data=data.clone();let persist=persist.clone();Callback::from(move|v:String|{let mut d=(*data).clone();d.display_name=v;persist.emit(d)})};html!{<div class="panel profile"><span class="avatar">{"M"}</span><span class="eyebrow">{"THIS IS YOUR SPACE"}</span><h2>{if data.display_name.is_empty(){"MR.Munna"}else{&data.display_name}}</h2>{input("Display name",&data.display_name,Callback::from(move|e|save.emit(value(e))),"text")}{input("Date of birth",&data.birthdate,{let data=data.clone();let persist=persist.clone();Callback::from(move|e|{let mut d=(*data).clone();d.birthdate=value(e);persist.emit(d)})},"date")}<p class="muted">{"Saved in this browser. Use Backup & settings to move your data."}</p></div>}},
  Page::Backup=>{let export={let data=data.clone();let notice=notice.clone();Callback::from(move|_|{let Ok(text)=storage::export(&data)else{notice.set("Backup failed".into());return};if text.len()<40{notice.set("Backup failed: empty output".into());return}if let Some(w)=web_sys::window(){if let Some(doc)=w.document(){let a: web_sys::HtmlAnchorElement=doc.create_element("a").unwrap().unchecked_into();let array=js_sys::Array::new();array.push(&wasm_bindgen::JsValue::from_str(&text));if let Ok(blob)=web_sys::Blob::new_with_str_sequence(&array){if let Ok(url)=web_sys::Url::create_object_url_with_blob(&blob){a.set_href(&url);a.set_download("MR-Munna-Web-Backup.json");a.click();let _=web_sys::Url::revoke_object_url(&url);notice.set(format!("Backup prepared: {} bytes",text.len()))}}}}})};let restore={let persist=persist.clone();let notice=notice.clone();Callback::from(move|e:Event|{let input:HtmlInputElement=e.target_unchecked_into();let Some(file)=input.files().and_then(|f|f.get(0))else{return};let reader=web_sys::FileReader::new().unwrap();let cb=wasm_bindgen::closure::Closure::<dyn FnMut(_)>::new({let persist=persist.clone();let notice=notice.clone();let reader=reader.clone();move|_:web_sys::Event|{let text=reader.result().ok().and_then(|v|v.as_string()).unwrap_or_default();match storage::validate_backup(&text){Ok(d)=>persist.emit(d),Err(e)=>notice.set(e)}}});reader.set_onload(Some(cb.as_ref().unchecked_ref()));cb.forget();let _=reader.read_as_text(&file)})};html!{<><div class="page-heading"><div><span class="eyebrow">{"YOUR STORY, IN YOUR HANDS"}</span><h2>{"Backup & settings"}</h2><p>{"Keep a copy of your entries before changing phones or clearing browser data."}</p></div></div><div class="panel backup"><h3>{"Backup & restore"}</h3><p>{"Your data is stored on this device, in this browser. Export a copy regularly."}</p><button class="button primary" onclick={export}>{"Download backup"}</button><label class="button subtle file-label">{"Restore from backup"}<input type="file" accept=".json,application/json" onchange={restore}/></label><p class="muted">{"Restoring replaces this browser's current entries and sheets. Keep a backup first."}</p></div></>}}
 };
 html!{<div class="shell"><aside class={if *drawer{"sidebar open"}else{"sidebar"}}><div class="brand"><img src="brand_icon.webp" alt="MR.Munna icon"/><div><b>{"MR.Munna"}</b><small>{"ADVENTURE JOURNEY"}</small></div><button class="close-menu" onclick={let d=drawer.clone();Callback::from(move |_|d.set(false))}>{"✕"}</button></div><div class="nav-label">{"EXPLORE YOUR WORLD"}</div><nav>{for Page::all().iter().map(|(p,label,icon)|{let p=*p;let nav=navigate.clone();html!{<button class={if current==p{"nav-item selected"}else{"nav-item"}} onclick={Callback::from(move |_|nav.emit(p))}><span>{icon}</span>{label}</button>}})}</nav><div class="sidebar-foot">{"✦ Your life. Your story."}</div></aside>{if *drawer{html!{<div class="scrim" onclick={let d=drawer.clone();Callback::from(move |_|d.set(false))}/>}}else{html!{}}}<div class="main"><header class="topbar"><button class="menu-toggle" onclick={let d=drawer.clone();Callback::from(move |_|d.set(true))}>{"☰"}</button><div><span class="eyebrow">{"MR.MUNNA · ADVENTURE JOURNEY"}</span><h1>{current.title()}</h1></div><span class="top-date">{today()}</span><span class="top-avatar">{"M"}</span></header><main class="content">{content}</main><footer>{"Made for the journey ahead · MR.Munna"}</footer>{if !notice.is_empty(){html!{<button class="toast" onclick={let notice=notice.clone();Callback::from(move |_|notice.set(String::new()))}>{(*notice).clone()} {"✕"}</button>}}else{html!{}}}</div></div>}
}
fn main(){yew::Renderer::<App>::with_root(web_sys::window().unwrap().document().unwrap().get_element_by_id("app").unwrap()).render()}
